# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(662, 459)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 641, 441))
        self.tabWidget.setStyleSheet(_fromUtf8(""))
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.verticalLayout.addWidget(self.tabWidget)
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.label_3 = QtGui.QLabel(self.tab1)
        self.label_3.setGeometry(QtCore.QRect(50, 110, 91, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.pb_addMaster = QtGui.QPushButton(self.tab1)
        self.pb_addMaster.setGeometry(QtCore.QRect(470, 180, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_addMaster.setFont(font)
        self.pb_addMaster.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pb_addMaster.setObjectName(_fromUtf8("pb_addMaster"))
        self.le_job_num = QtGui.QLineEdit(self.tab1)
        self.le_job_num.setGeometry(QtCore.QRect(190, 30, 241, 35))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_job_num.sizePolicy().hasHeightForWidth())
        self.le_job_num.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.le_job_num.setFont(font)
        self.le_job_num.setObjectName(_fromUtf8("le_job_num"))
        self.pb_reset = QtGui.QPushButton(self.tab1)
        self.pb_reset.setGeometry(QtCore.QRect(140, 260, 151, 51))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_reset.sizePolicy().hasHeightForWidth())
        self.pb_reset.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(14)
        self.pb_reset.setFont(font)
        self.pb_reset.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pb_reset.setAutoDefault(True)
        self.pb_reset.setDefault(True)
        self.pb_reset.setObjectName(_fromUtf8("pb_reset"))
        self.pb_create_project = QtGui.QPushButton(self.tab1)
        self.pb_create_project.setGeometry(QtCore.QRect(350, 260, 151, 51))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_create_project.sizePolicy().hasHeightForWidth())
        self.pb_create_project.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(14)
        self.pb_create_project.setFont(font)
        self.pb_create_project.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pb_create_project.setAutoDefault(True)
        self.pb_create_project.setObjectName(_fromUtf8("pb_create_project"))
        self.le_line_num = QtGui.QLineEdit(self.tab1)
        self.le_line_num.setGeometry(QtCore.QRect(190, 105, 241, 35))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_line_num.sizePolicy().hasHeightForWidth())
        self.le_line_num.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.le_line_num.setFont(font)
        self.le_line_num.setObjectName(_fromUtf8("le_line_num"))
        self.ecb_master_flow = QtGui.QComboBox(self.tab1)
        self.ecb_master_flow.setGeometry(QtCore.QRect(187, 180, 250, 42))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ecb_master_flow.sizePolicy().hasHeightForWidth())
        self.ecb_master_flow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.ecb_master_flow.setFont(font)
        self.ecb_master_flow.setEditable(True)
        self.ecb_master_flow.setObjectName(_fromUtf8("ecb_master_flow"))
        self.label_4 = QtGui.QLabel(self.tab1)
        self.label_4.setGeometry(QtCore.QRect(50, 190, 131, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_2 = QtGui.QLabel(self.tab1)
        self.label_2.setGeometry(QtCore.QRect(50, 40, 91, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.googKMZ = QtGui.QPushButton(self.tab2)
        self.googKMZ.setGeometry(QtCore.QRect(40, 130, 141, 61))
        self.googKMZ.setObjectName(_fromUtf8("googKMZ"))
        self.flatIrons = QtGui.QPushButton(self.tab2)
        self.flatIrons.setGeometry(QtCore.QRect(240, 130, 141, 61))
        self.flatIrons.setObjectName(_fromUtf8("flatIrons"))
        self.tabWidget.addTab(self.tab2, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pb_reset.clicked.connect(self.le_job_num.clear)
        self.pb_reset.clicked.connect(self.le_line_num.clear)
        MainWindow.setTabOrder(self.le_job_num, self.le_line_num)
        MainWindow.setTabOrder(self.le_line_num, self.ecb_master_flow)
        MainWindow.setTabOrder(self.ecb_master_flow, self.pb_addMaster)
        MainWindow.setTabOrder(self.pb_addMaster, self.pb_create_project)
        MainWindow.setTabOrder(self.pb_create_project, self.pb_reset)
        MainWindow.setTabOrder(self.pb_reset, self.tabWidget)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "SeisUp Project Creator", None))
        self.label_3.setText(_translate("MainWindow", "Line #:", None))
        self.pb_addMaster.setText(_translate("MainWindow", "Add Master", None))
        self.pb_reset.setText(_translate("MainWindow", "Reset", None))
        self.pb_create_project.setText(_translate("MainWindow", "Create Project", None))
        self.label_4.setText(_translate("MainWindow", "Master Flow:", None))
        self.label_2.setText(_translate("MainWindow", "Job #:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Project Information", None))
        self.googKMZ.setText(_translate("MainWindow", "Google Earth", None))
        self.flatIrons.setText(_translate("MainWindow", "FlatIrons", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Line Resources", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

